[[lotus]]
  name = "Getting started"
  weight = 10
  identifier = "lotus-getting-started"
  url = "/lotus/getting-started"

[[lotus]]
  name = "Installation"
  weight = 20
  identifier = "lotus-installation"
  url = "/lotus/installation"

[[lotus]]
  name = "Lotus Configuration"
  weight = 30
  identifier = "lotus-config"
  url = "/lotus/lotus-config"

[[lotus]]
  name = "Node Management"
  weight = 40
  identifier = "lotus-node-management"
  url = "/lotus/node-management"

[[lotus]]
  name = "Project"
  weight = 50
  identifier = "project"
  url = "/lotus/project"

[[storage-providers]]
  name = "Getting Started"
  weight = 10
  identifier = "miner-init"
  url = "/storage-providers/getting-started"

[[storage-providers]]
  name = "Setup and Configuration"
  weight = 20
  identifier = "lotus-miner-config"
  url = "/storage-providers/lotus-miner-config"

[[storage-providers]]
  name = "Daily Operations"
  weight = 30
  identifier = "lotus-miner-operation"
  url = "/storage-providers/lotus-miner-operation"

[[storage-providers]]
  name = "Seal Workers"
  weight = 40
  identifier = "seal-workers"
  url = "/storage-providers/seal-workers"

[[developers]]
  name = "Developers"
  weight = 10
  identifier = "developers"
  url = "/developers"

[[tutorials]]
  name = "Lotus Tutorials"
  weight = 10
  identifier = "lotus-tutorials"
  url = "/tutorials/lotus-tutorials"

[[tutorials]]
  name = "Lotus Miner Tutorials"
  weight = 20
  identifier = "lotus-miner-tutorials"
  url = "/tutorials/lotus-miner-tutorials"

[[main]]
  name = "Lotus"
  url = "/lotus/getting-started/what-is-lotus"
  weight = 10

[[main]]
  name = "Developers"
  url = "/developers/api-access"
  weight = 20

[[main]]
  name = "Storage Providers"
  url = "/storage-providers/getting-started/overview"
  weight = 30

[[main]]
  name = "Tutorials"
  url = "/tutorials/lotus-tutorials/store-and-retrieve"
  weight = 40

[[main]]
  name = "Knowledge Base"
  url = "/kb"
  identifier = "kb"
  weight = 50

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 60

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/filecoin-project/lotus-docs"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/protocollabs"
  weight = 20

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
